schema: book

datasource:
  ds0: !!com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.154.129:3306?sharding0
    username: root
    password: dummy
    driverClassName: com.mysql.jdbc.Driver
  ds1: !!com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.154.129:3306?sharding1
    username: root
    password: dummy
    driverClassName: coHikariDataSourcem.mysql.jdbc.Driver

shardingRule:
  defaultDataSourceName: ds0
  defaultDatabaseStrategy:
    inline:
      shardingColumn: id
      algorithmExpression: ds${id % 2}
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
  tables:
    book:
      actualDataNodes: ds$->{0..1}.book$->{0..2}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: book$->{id % 3}
          keyGeneratorColumnName: id

props:
  sql.show: true

