schema: book

datasource:
  ds0: !!com.alibaba.druid.pool.DruidDataSource
    url:
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver
  ds1: !!com.alibaba.druid.pool.DruidDataSource
    url:
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver

shardingRule:
  defaultDataSourceName: ds0
  defaultDatabaseStrategy:
    inline:
      shardingColumn: id
      algorithmExpression: ds${id % 2}
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
  tables:
    book:
      actualDataNodes: ds$->{0..1}.book$->{0..2}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: book$->{id % 3}
          keyGeneratorColumnName: id

props:
  sql.show: true

